yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.Author.as_view(), name='author'),
    path('tech/', views.Tech.as_view(), name='tech'),
]

yatube/groups/urls.py
from django.urls import path

from . import views

app_name = 'groups'

urlpatterns = [
    path('<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('group_list/<slug:slug>/', views.group_posts, name='group_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edition'),
    path('profile/<str:username>/', views.profile, name='profile'),

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    # path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('group/', include('groups.urls', namespace='groups')),
    path('', include('posts.urls', namespace='posts')),
]

yatube/groups/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

yatube/groups/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from .models import Group


def group_posts(request, slug):
    template = 'groups/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    title = group.title
    page_title = f'Посты группы {title}.'
    posts = group.posts.all().order_by('-pub_date')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group_slug': slug,
        'posts': page_obj,
        'group_title': title,
        'page_title': page_title,
    }
    return render(request, template, context)

yatube/templates/groups/group_list.html
{% extends 'base.html' %}
{% block content %}
      <div class="container py-5">
        <h1>
          <p>
            Посты группы {{ group_title }}
          </p>
        </h1>
        {% for post in posts %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.first_name }} {{ post.author.last_name }},
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>      
            <p>
              {{ post.text|safe }}
            </p>
            <p>
            <a href="{% url 'posts:post_detail' post.pk %}">Читать полностью</a>
            </p>
            <p>
            {% if request.user == post.author %}
              <p>
                <a href="{% url 'posts:post_edition' post.pk %}">
                  Редактировать пост
                </a>
              </p>
            {% endif %}      
          </article>
          {% if not forloop.last %}
            <hr>
          {% endif %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
      </div>
  {% endblock content %}