yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.Author.as_view(), name='author'),
    path('tech/', views.Tech.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('group_list/<slug:slug>/', views.group_posts, name='group_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edition'),
    path('profile/<str:username>/', views.profile, name='profile'),

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    # path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('group/', include('groups.urls', namespace='groups')),
    path('', include('posts.urls', namespace='posts')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.fields.related import ForeignKey

from groups.models import Group

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True, null=True
    )

    def __str__(self) -> str:
        return self.text

yatube/posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from groups import models as gm


User = get_user_model()


class CreatePost(forms.Form):
    text = forms.CharField(label="Текст поста", help_text='Текст нового поста', widget=forms.Textarea, required=True)
    group = forms.ModelChoiceField(label="Группа", help_text='Группа, к которой будет относиться пост', queryset=gm.Group.objects.all(), required=False)

yatube/posts/views.py
from re import template
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.shortcuts import get_object_or_404

from . import forms
from .models import Post
from .models import Group

User = get_user_model()


def index(request):
    template = 'posts/index.html'
    page_title = 'Главная страница Yatube'
    title = 'Последние обновления на сайте'
    posts = Post.objects.order_by('-pub_date')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'posts': page_obj,
        'title': title,
        'page_title': page_title,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    title = group.title
    posts = group.posts.all().order_by('-pub_date')[:10]
    context = {
        'group_slug': slug,
        'group_ten_posts': posts,
        'group_title': title,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    user_c = get_object_or_404(User, username=username)
    posts = user_c.posts.all().order_by('-pub_date')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    posts_total = posts.count()
    user_name = f'{user_c.first_name} {user_c.last_name}'
    title = f'Профайл пользователя {user_name}'
    context = {
        'title': title,
        'posts': page_obj,
        'user': user_c,
        'posts_total': posts_total,
        'user_name': user_name
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    group = post.group
    author = f'{post.author.first_name} {post.author.last_name}'
    date = post.pub_date
    posts_count = post.author.posts.count()
    title = f'Пост {post.text[:30]}'
    username = post.author.username
    text = post.text
    context = {
        'title': title,
        'author': author,
        'group': group,
        'date': date,
        'posts_count': posts_count,
        'username': username,
        'text': text,
        'post_id': post_id
    }
    return render(request, template, context)


def post_create(request):
    if request.user.is_authenticated:
        template = 'posts/create_post.html'
        if request.method == 'POST':
            PostForm = forms.CreatePost(request.POST)
            if PostForm.is_valid():
                new_post = Post(text=PostForm.cleaned_data['text'], author=request.user, group=PostForm.cleaned_data['group'])
                new_post.save()
                return redirect('posts:index')

            PostForm = forms.CreatePost(request.POST)
            context = {
                'form': PostForm,
                'request': request,
            }
            return render(request, template, context)

        PostForm = forms.CreatePost()
        context = {
            'form': PostForm,
            'request': request,
        }
        return render(request, template, context)
    else:
        return redirect('users:login')


def post_edit(request, post_id):
    post_obj = get_object_or_404(Post, pk=post_id)
    if request.user.is_authenticated and request.user == post_obj.author:
        template = 'posts/create_post.html'
        data = {'text': post_obj.text, 'group': post_obj.group}
        form = forms.CreatePost(initial=data)
        context = {
            'is_edit': True,
            'form': form
        }
        return render(request, template, context)
    else:
        return redirect('posts:post_detail', post_id=post_id)
    

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
  {% if is_edit %}
    Редактирование поста
  {% else %}
    Новый пост
  {% endif %} 
  {% endblock title %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактирование поста
                {% else %}
                  Новый пост
                {% endif %}             
              </div>
              <div class="card-body">        
                <form method="post" action="{% url 'posts:post_create' %}">
                  {% csrf_token %}       
                  {% for field in form %} 
                    <div class="form-group row my-3">
                      <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                          {% if field.field.required %}
                            <span class="required text-danger">*</span>
                          {% endif %}
                      </label>
                      {{ field|addclass:'form-control' }} 
                        {% if field.help_text %}
                          <small 
                            id="{{ field.id_for_label }}-help"
                            class="form-text text-muted"
                          >
                            {{ field.help_text|safe }}
                          </small>
                        {% endif %}
                    </div>
                  {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %} 
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
      <div class="container py-5">
        <h1>
          <p>
            Посты группы {{ group_title }}
          </p>
        </h1>
        {% for post in group_ten_posts %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date }}
              </li>
            </ul>      
            <p>
              {{ post.text|safe }}
            </p>         
          </article>
          {% if not forloop.last %}
            <hr>
          {% endif %}
        {% endfor %}
      </div>  
{% endblock content%}

yatube/templates/posts/index.html
{% extends 'base.html' %}
    {% block content %}
      <div class="container py-5">     
        <h1>{{ title }}</h1>
        {% for post in posts %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date }}
            </li>
          </ul>      
          <p>
            {{ post.text|safe }}
          </p>
          {% if post.group is not None %}
          <p>
          <a href="{% url 'groups:group_list' post.group.slug %}">Все посты группы</a>
          </p>
          {% endif %}
        </article>
          {% if not forloop.last %}
            <hr>
          {% endif %}
        {% endfor %} 
        {% include 'includes/paginator.html' %}
      </div>  
  {% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
<div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ date|date:"d E Y" }} 
            </li>
            {% if group %}
              <li class="list-group-item">
                Группа: {{ group }}
                <a href="{% url 'groups:group_list' group.slug %}">
                  все записи группы
                </a>
              </li>
              {% endif %}
              <li class="list-group-item">
                Автор: {{ author }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ posts_count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' username %}">
                все посты пользователя
              </a>
            </li>
            {% if request.user.username == username %}
              <li class="list-group-item">
                <a href="{% url 'posts:post_edition' post_id %}">
                  редактировать пост
                </a>
              </li>
          {% endif %}
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
           {{ text|safe }}
          </p>
        </article>
      </div> 
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
<div class="container py-5">        
        <h1>Все посты пользователя {{ user_name }} </h1>
        <h3>Всего постов: {{ posts_total }} </h3>   
        {% for post in posts %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.first_name }} {{ post.author.last_name }},
                <a href="{% url 'posts:profile' user.username %}">все посты пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>      
            <p>
              {{ post.text|safe }}
            </p>       
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>  
          </article>
          {% if post.group %}
          <a href="{% url 'groups:group_list' post.group.slug %}">все записи группы {{ post.group }}</a> 
          {% endif %}
          {% if not forloop.last %}
            <hr>
          {% endif %}
          {% endfor %}
        {% include 'includes/paginator.html' %} 
</div>
{% endblock content %}

yatube/templates/posts/update_post.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Редактировать пост</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">              
              <a class="nav-link" href="../about/author.html">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../about/tech.html">
                Технологии
              </a>
            </li>
            <!-- пункты меню видны только авторизованному пользователю -->
            <li class="nav-item">
              <a class="nav-link active" href="../posts/create_post.html">
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/password_change_form.html">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/logged_out.html">Выйти</a>
            </li>
            <li>
              Пользователь: leo
            <li>
            <!-- конец пункты меню видны только авторизованному пользователю -->
            <!-- пункты меню видны только неавторизованному пользователю -->
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/login.html">
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/signup.html">Регистрация</a>
            </li>
            <!-- конец пункты меню видны только неавторизованному пользователю -->        
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Редактировать пост             
              </div>
              <div class="card-body">        
                <form method="post" action="../posts/create_post.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="">---------</option>
                      <option value="1" selected>Группа: Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Добавить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>